name: nexoclom_dev
channels:
  - anaconda
  - http://ssb.stsci.edu/astroconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - ipython
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - anaconda::astropy
  - astroquery
  - postgresql
  - dash
  - plotly
  - bokeh
  - selenium
  - conda-forge::firefox
  - conda-forge::geckodriver
  - pytest
  - pip:
    - psycopg2
    - periodictable
    - spiceypy
    - sphinx
    - stsci_rtd_theme
    - statsmodels

