name: nexoclom
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - python=3.10
  - poetry
  - postgresql
  - mongodb
  - ipython
  - pip
  - pytest
  - pip:
    - statsmodels
    - nexoclom
    - MESSENGERuvvs

variables:
  PGDATA: $HOME/.postgres/main
  NEXOCLOMCONFIG : $HOME/.nexoclom
